version: '3'

services:

  redmine:
    build: ./passenger
    restart: always
    ports:
      - 8080:3000
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_PASSWORD=example
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_PLUGINS_MIGRATE=1
    volumes:
      - redmine:/usr/src/redmine
    ports:
      - 8019:3000
    depends_on:
      - db
 
  db:
    image: postgres:alpine
    restart: always
    environment:
     - POSTGRES_PASSWORD=example
     - POSTGRES_DB=redmine
     - POSTGRES_USER=redmine
    volumes:
      - db:/var/lib/postgresql/data
  
      

volumes:
  redmine:
  db:
  
      
