version: '3'

services:

  redmine:
    build: ./passenger
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: example
    volumes:
      - redmine:/usr/src/redmine/files
 
  db:
    image: postgres:alpine
    restart: always
    environment:
     POSTGRES_PASSWORD=example
     POSTGRES_DB=redmine
     POSTGRES_USER=redmine
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  redmine:
  db:
  
      
